apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluentd.conf: |
    <source>
      @type tail
      path "/var/log/containers/*.log"
      pos_file "/fluentd/logs/fluentd-containers.pos"
      tag "kubernetes.*"
      format none  # Não use 'json' aqui, pois os logs não são JSON
      <parse>
        @type none
      </parse>
    </source>

    <match kubernetes.**>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port 9200
      logstash_format true
      logstash_prefix "fluentd"
      logstash_dateformat "%Y.%m.%d"  # Isso cria um índice diário
      flush_interval 5s
      <buffer>
        flush_interval 5s
      </buffer>
      <filter kubernetes.**>
        @type record_transformer
        <record>
          timestamp ${time}
        </record>
      </filter>
    </match>

    <system>
      log_level debug
    </system>