{
 "title": "App Web Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Percentage Success",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 * sum(rate(http_requests_total{status_code=~\"2..|3..\"}[5m]))) / sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration (D): The amount of time to process a request",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[10m])) by (le, container))",
     "legendFormat": "p90 {{container}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[10m])) by (le, container))",
     "legendFormat": "Median {{container}}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum[10m]) / rate(http_request_duration_seconds_count[10m])",
     "legendFormat": "Average {{container}}"
    }
   ]
  },
  {
   "title": "Rate (R): Number of success requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_total{status_code=~\"2..|3..\"}[1m])) by (method, status_code))",
     "legendFormat": "{{method}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Errors (E): The number of failed requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_errors_total[1m])) by (method, status_code))",
     "legendFormat": "{{method}}-{{status_code}}"
    }
   ]
  }
 ]
}