---
# Allows you to add config files
apmConfig:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
    logging:
      level: debug

    queue: {}

    output.elasticsearch:
      hosts: ["https://elasticsearch-master:9200"]
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
      ## If SSL is enabled
      protocol: https
      ssl.verification_mode: none
    
    apm-server:
      host: "0.0.0.0:8200" # default
      rum.enabled: true
      kibana:
        enabled: true
        host: http://kibana-kibana.monitoring:5601
        protocol: "http"
        username: "${ELASTICSEARCH_USERNAME}"
        password: "${ELASTICSEARCH_PASSWORD}"

replicas: 1