apiVersion: v1
kind: Service
metadata:
  name: app-web-service
  namespace: pedro-dias
spec:
  selector:
    app: app-web          # seletor para identificar os pods que deveriam receber o tráfego
  ports:
    - protocol: TCP
      port: 80          # porta exposta do serviço
      targetPort: 3000    # porta destino no pod
  type: ClusterIP       # service typ