apiVersion: v1
kind: Service
metadata:
  name: app-web-service
  namespace: pedro-dias
  labels:
    app: app-web  # Adicionando a label "app: app-web" aqui
spec:
  selector:
    app: app-web          # seletor para identificar os pods que deveriam receber o tráfego
  ports:
    - name: http
      protocol: TCP
      port: 80          # porta exposta do serviço
      targetPort: 3000    # porta destino no pod
  type: ClusterIP       # service typ